# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.4434
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.7925 
    max_position: 2.7925 
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.6179
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -.5760 
    max_position: 2.6180 
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.7925
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -.9076 
    max_position: 2.8798 
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.9813
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -3.3161 
    max_position: 3.3161 
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.7595
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -1.8500 
    max_position: 1.9199 
  joint_6:
    has_velocity_limits: true
    max_velocity: 8.3775
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -.3491 
    max_position: .3491 
